lint:
  stage: .pre
  image: alpine
  script:
    - apk add --no-cache git
    - find specs/ -name '*.md' -exec grep -L 'SPDX-FileCopyrightText' {} \;
    - echo "Lint complete"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
